# Importing raw data

### Converting txt file in json values into List of lines

In [1]:
import json
with open(r".\transactions.txt") as file:
    raw_data = file.readlines()
processed_raw_data = [json.loads(line) for line in raw_data]

In [4]:
processed_raw_data

[{'accountNumber': '737265056',
  'customerId': '737265056',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-08-13T14:27:32',
  'transactionAmount': 98.55,
  'merchantName': 'Uber',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'rideshare',
  'currentExpDate': '06/2023',
  'accountOpenDate': '2015-03-14',
  'dateOfLastAddressChange': '2015-03-14',
  'cardCVV': '414',
  'enteredCVV': '414',
  'cardLast4Digits': '1803',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '737265056',
  'customerId': '737265056',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-10-11T05:05:54',
  'transactionAmount': 74.51,
  'merchantName': 'AMC #191138',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'entertainment',
  'cardPresent': True,
  'currentExpDate': '02/2024',
  'accountOpenDate': '2015-03-14',
  'dateOfLastAddressChange': '2015-03-14',
  'cardCVV': '486',
  'enteredCVV': '486',
  'cardLast4Digits': '767',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '737265056',
  'customerId': '737265056',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-11-08T09:18:39',
  'transactionAmount': 7.47,
  'merchantName': 'Play Store',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'mobileapps',
  'currentExpDate': '08/2025',
  'accountOpenDate': '2015-03-14',
  'dateOfLastAddressChange': '2015-03-14',
  'cardCVV': '486',
  'enteredCVV': '486',
  'cardLast4Digits': '767',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '737265056',
  'customerId': '737265056',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-12-10T02:14:50',
  'transactionAmount': 7.47,
  'merchantName': 'Play Store',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'mobileapps',
  'currentExpDate': '08/2025',
  'accountOpenDate': '2015-03-14',
  'dateOfLastAddressChange': '2015-03-14',
  'cardCVV': '486',
  'enteredCVV': '486',
  'cardLast4Digits': '767',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-03-24T21:04:46',
  'transactionAmount': 71.18,
  'merchantName': 'Tim Hortons #947751',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '10/2029',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-04-19T16:24:27',
  'transactionAmount': 30.76,
  'merchantName': 'In-N-Out #422833',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '01/2020',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-05-21T14:50:35',
  'transactionAmount': 57.28,
  'merchantName': 'Krispy Kreme #685312',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '05/2020',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-06-03T00:31:21',
  'transactionAmount': 9.37,
  'merchantName': 'Shake Shack #968081',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '05',
  'posConditionCode': '01',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '01/2021',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 4990.63,
  'currentBalance': 9.37,
  'transactionDateTime': '2016-06-10T01:21:46',
  'transactionAmount': 523.67,
  'merchantName': 'Burger King #486122',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '08/2032',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'acqCountry': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-07-11T10:47:16',
  'transactionAmount': 164.37,
  'merchantName': 'Five Guys #510989',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '05',
  'posConditionCode': '08',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '04/2020',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-09-07T20:22:47',
  'transactionAmount': 160.18,
  'merchantName': "Auntie Anne's #747964",
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '08',
  'merchantCategoryCode': 'fastfood',
  'cardPresent': True,
  'currentExpDate': '05/2023',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 5000.0,
  'transactionDateTime': '2016-12-07T16:34:04',
  'transactionAmount': 40.75,
  'merchantName': 'GreenCook',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'food_delivery',
  'currentExpDate': '08/2024',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 4959.25,
  'currentBalance': 40.75,
  'transactionDateTime': '2016-12-14T10:00:35',
  'transactionAmount': 40.75,
  'merchantName': 'GreenCook',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'food_delivery',
  'currentExpDate': '08/2024',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 4918.5,
  'currentBalance': 81.5,
  'transactionDateTime': '2016-12-20T18:38:23',
  'transactionAmount': 40.75,
  'merchantName': 'GreenCook',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'food_delivery',
  'currentExpDate': '08/2024',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '830329091',
  'customerId': '830329091',
  'creditLimit': 5000.0,
  'availableMoney': 4877.75,
  'currentBalance': 122.25,
  'transactionDateTime': '2016-12-28T06:43:01',
  'transactionAmount': 40.75,
  'merchantName': 'GreenCook',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'food_delivery',
  'currentExpDate': '08/2024',
  'accountOpenDate': '2015-08-06',
  'dateOfLastAddressChange': '2015-08-06',
  'cardCVV': '885',
  'enteredCVV': '885',
  'cardLast4Digits': '3143',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2500.0,
  'transactionDateTime': '2016-01-02T11:19:46',
  'transactionAmount': 30.08,
  'merchantName': 'Washington Repair',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '12/2031',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '206',
  'enteredCVV': '206',
  'cardLast4Digits': '8522',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2469.92,
  'currentBalance': 30.08,
  'transactionDateTime': '2016-01-16T01:01:27',
  'transactionAmount': 41.25,
  'merchantName': 'Eazy Tire',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '09/2027',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '206',
  'enteredCVV': '206',
  'cardLast4Digits': '8522',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2428.67,
  'currentBalance': 71.33,
  'transactionDateTime': '2016-01-26T14:04:22',
  'merchantName': 'Convenient Auto Services',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'currentExpDate': '08/2025',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '206',
  'enteredCVV': '206',
  'cardLast4Digits': '8522',
  'transactionType': 'ADDRESS_VERIFICATION',
  'echoBuffer': '',
  'transactionAmount': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'cardPresent': False,
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2428.67,
  'currentBalance': 71.33,
  'transactionDateTime': '2016-01-29T07:17:39',
  'transactionAmount': 124.21,
  'merchantName': 'Convenient Auto Services',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '05',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '08/2032',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '579',
  'enteredCVV': '579',
  'cardLast4Digits': '4219',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2304.46,
  'currentBalance': 195.54,
  'transactionDateTime': '2016-01-29T07:33:15',
  'transactionAmount': 196.07,
  'merchantName': 'Shell Auto Body',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '08/2022',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '579',
  'enteredCVV': '539',
  'cardLast4Digits': '4219',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2108.39,
  'currentBalance': 391.61,
  'transactionDateTime': '2016-01-29T21:44:33',
  'transactionAmount': 4.11,
  'merchantName': 'Convenient Auto Services',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '05',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '11/2027',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '579',
  'enteredCVV': '579',
  'cardLast4Digits': '4219',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2500.0,
  'transactionDateTime': '2016-02-06T08:16:46',
  'transactionAmount': 108.86,
  'merchantName': 'Fast Auto Services',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '09',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '08/2028',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '206',
  'enteredCVV': '206',
  'cardLast4Digits': '8522',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'currentBalance': 0.0,
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2391.14,
  'currentBalance': 108.86,
  'transactionDateTime': '2016-02-12T03:47:24',
  'transactionAmount': 28.23,
  'merchantName': 'Washington Repair',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '05',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '09/2032',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '579',
  'enteredCVV': '579',
  'cardLast4Digits': '4219',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,
  'availableMoney': 2362.91,
  'currentBalance': 137.09,
  'transactionDateTime': '2016-02-22T17:32:13',
  'transactionAmount': 26.17,
  'merchantName': 'Washington Repair',
  'acqCountry': 'US',
  'merchantCountryCode': 'US',
  'posEntryMode': '02',
  'posConditionCode': '01',
  'merchantCategoryCode': 'auto',
  'cardPresent': True,
  'currentExpDate': '10/2028',
  'accountOpenDate': '2015-10-13',
  'dateOfLastAddressChange': '2015-10-13',
  'cardCVV': '579',
  'enteredCVV': '579',
  'cardLast4Digits': '4219',
  'transactionType': 'PURCHASE',
  'echoBuffer': '',
  'merchantCity': '',
  'merchantState': '',
  'merchantZip': '',
  'posOnPremises': '',
  'recurringAuthInd': '',
  'expirationDateKeyInMatch': False,
  'isFraud': False},
 {'accountNumber': '574788567',
  'customerId': '574788567',
  'creditLimit': 2500.0,

### Load into Pandas dataframe i.e. tabular from

In [5]:
import pandas as pd
dataframe = pd.DataFrame(processed_raw_data)

In [6]:
dataframe.head()                              # 1st 5 rows

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,...,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud
0,737265056,737265056,5000.0,5000.0,2016-08-13T14:27:32,98.55,Uber,US,US,02,...,,0.0,,,,False,,,False,False
1,737265056,737265056,5000.0,5000.0,2016-10-11T05:05:54,74.51,AMC #191138,US,US,09,...,,0.0,,,,True,,,False,False
2,737265056,737265056,5000.0,5000.0,2016-11-08T09:18:39,7.47,Play Store,US,US,09,...,,0.0,,,,False,,,False,False
3,737265056,737265056,5000.0,5000.0,2016-12-10T02:14:50,7.47,Play Store,US,US,09,...,,0.0,,,,False,,,False,False
4,830329091,830329091,5000.0,5000.0,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,02,...,,0.0,,,,True,,,False,False

In [7]:
dataframe.describe(include='O')

,accountNumber,customerId,transactionDateTime,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,...,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,merchantCity,merchantState,merchantZip,posOnPremises,recurringAuthInd
count,786363,786363,786363,786363,786363,786363,786363,786363,786363,786363,...,786363,786363,786363,786363,786363,786363,786363,786363,786363,786363
unique,5000,5000,776637,2490,5,5,6,4,19,165,...,899,976,5246,4,1,1,1,1,1,1
top,380680241,380680241,2016-05-28T14:24:41,Uber,US,US,05,01,online_retail,03/2029,...,869,869,593,PURCHASE,,,,,,
freq,32850,32850,4,25613,774709,778511,315035,628787,202156,5103,...,33749,33424,32946,745193,786363,786363,786363,786363,786363,786363

In [8]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 786363 entries, 0 to 786362
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   accountNumber             786363 non-null  object
 1   customerId                786363 non-null  object
 2   creditLimit               786363 non-null  float64
 3   availableMoney            786363 non-null  float64
 4   transactionDateTime       786363 non-null  object
 5   transactionAmount         786363 non-null  float64
 6   merchantName              786363 non-null  object
 7   acqCountry                786363 non-null  object
 8   merchantCountryCode       786363 non-null  object
 9   posEntryMode              786363 non-null  object
 10  posConditionCode          786363 non-null  object
 11  merchantCategoryCode      786363 non-null  object
 12  currentExpDate            786363 non-null  object
 13  accountOpenDate           786363 non-null  object
 14  dateOfLastAddressChange   786363 non-null  object
 15  cardCVV                   786363 non-null  object
 16  enteredCVV                786363 non-null  object
 17  cardLast4Digits           786363 non-null  object
 18  transactionType           786363 non-null  object
 19  echoBuffer                786363 non-null  object
 20  currentBalance            786363 non-null  float64
 21  merchantCity              786363 non-null  object
 22  merchantState             786363 non-null  object
 23  merchantZip               786363 non-null  object
 24  cardPresent               786363 non-null  bool
 25  posOnPremises             786363 non-null  object
 26  recurringAuthInd          786363 non-null  object
 27  expirationDateKeyInMatch  786363 non-null  bool
 28  isFraud                   786363 non-null  bool
dtypes: bool(3), float64(4), object(22)
memory usage: 158.2+ MB

# Regression Analysis
A popular tool in data analytics, machine learning, advanced statistics, and econometrics, is regression analysis.

Roughly speaking, this is an equation which on one side has a variable, called a dependent variable, because its value will depend on the values of all variables you see on the other side.

The variables on the right side are all independent, or explanatory. Their role is to explain the value of the dependent variable.

There are more terms that can be used for these variables in the same context. The dependent variable can also be called a target, while the independent variables can be called predictors.
I will call the explanatory variables as ‘features’.

# Which model to choose ?
### Logistic Regression 
It is a type of a regression model whose dependent variable is binary. That is,it can assume one of two values : 0 or 1, True or False, Yes or No.
Considering the values of all our features from above summary , we want to be able to predict whether the dependent variable will take the value of 0 or 1.From above summary , we see that "isFraud" column is the dependent variable(or say Target) asking the question in Yes/No i.e. Boolean type. Thus, Logistic Regression Model is chosen. 

Note: Apart from logistic regression, there are many other types of equations that allow you to calculate the dependent variable in a different way. Logistic regression is just one of them – and it is one that has been used massively.

In [9]:
dataframe['isFraud'].value_counts()

False    773946
True      12417
Name: isFraud, dtype: int64

# Processing with features/variables/inputs

# 1st Check point
In case we need original dataframe in future

In [10]:
df=dataframe.copy()

In [11]:
# To take a detailed view of the whole data
pd.options.display.max_columns = None
pd.options.display.max_rows = 1000

In [12]:
display(df.head(100))

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud
0,737265056,737265056,5000.0,5000.00,2016-08-13T14:27:32,98.55,Uber,US,US,02,01,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,,0.00,,,,False,,,False,False
1,737265056,737265056,5000.0,5000.00,2016-10-11T05:05:54,74.51,AMC #191138,US,US,09,01,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.00,,,,True,,,False,False
2,737265056,737265056,5000.0,5000.00,2016-11-08T09:18:39,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.00,,,,False,,,False,False
3,737265056,737265056,5000.0,5000.00,2016-12-10T02:14:50,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.00,,,,False,,,False,False
4,830329091,830329091,5000.0,5000.00,2016-03-24T21:04:46,71.18,Tim Hortons #947751,US,US,02,01,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,True,,,False,False
5,830329091,830329091,5000.0,5000.00,2016-04-19T16:24:27,30.76,In-N-Out #422833,US,US,02,01,fastfood,01/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,True,,,False,False
6,830329091,830329091,5000.0,5000.00,2016-05-21T14:50:35,57.28,Krispy Kreme #685312,US,US,02,01,fastfood,05/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,True,,,False,False
7,830329091,830329091,5000.0,5000.00,2016-06-03T00:31:21,9.37,Shake Shack #968081,US,US,05,01,fastfood,01/2021,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,True,,,False,False
8,830329091,830329091,5000.0,4990.63,2016-06-10T01:21:46,523.67,Burger King #486122,,US,02,01,fastfood,08/2032,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,9.37,,,,True,,,False,False
9,830329091,830329091,5000.0,5000.00,2016-07-11T10:47:16,164.37,Five Guys #510989,US,US,05,08,fastfood,04/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,True,,,False,False
10,830329091,830329091,5000.0,5000.00,2016-09-07T20:22:47,160.18,Auntie Anne's #747964,US,US,02,08,fastfood,05/2023,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,True,,,False,False
11,830329091,830329091,5000.0,5000.00,2016-12-07T16:34:04,40.75,GreenCook,US,US,09,01,food_delivery,08/2024,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.00,,,,False,,,False,False
12,830329091,830329091,5000.0,4959.25,2016-12-14T10:00:35,40.75,GreenCook,US,US,09,01,food_delivery,08/2024,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,40.75,,,,False,,,False,False
13,830329091,830329091,5000.0,4918.50,2016-12-20T18:38:23,40.75,GreenCook,US,US,09,01,food_delivery,08/2024,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,81.50,,,,False,,,False,False
14,830329091,830329091,5000.0,4877.75,2016-12-28T06:43:01,40.75,GreenCook,US,US,09,01,food_delivery,08/2024,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,122.25,,,,False,,,False,False
15,574788567,574788567,2500.0,2500.00,2016-01-02T11:19:46,30.08,Washington Repair,US,US,02,01,auto,12/2031,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,0.00,,,,True,,,False,False
16,574788567,574788567,2500.0,2469.92,2016-01-16T01:01:27,41.25,Eazy Tire,US,US,09,01,auto,09/2027,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,30.08,,,,True,,,False,False
17,574788567,574788567,2500.0,2428.67,2016-01-26T14:04:22,0.00,Convenient Auto Services,US,US,09,01,auto,08/2025,2015-10-13,2015-10-13,206,206,8522,ADDRESS_VERIFICATION,,71.33,,,,False,,,False,False
18,574788567,574788567,2500.0,2428.67,2016-01-29T07:17:39,124.21,Convenient Auto Services,US,US,05,01,auto,08/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,71.33,,,,True,,,False,False
19,574788567,574788567,2500.0,2304.46,2016-01-29T07:33:15,196.07,Shell Auto Body,US,US,09,01,auto,08/2022,2015-10-13,2015-10-13,579,539,4219,PURCHASE,,195.54,,,,True,,,False,False
20,574788567,574788567,2500.0,2108.39,2016-01-29T21:44:33,4.11,Convenient Auto Services,US,US,05,01,auto,11/2027,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,391.61,,,,True,,,False,False
21,574788567,574788567,2500.0,2500.00,2016-02-06T08:16:46,108.86,Fast Auto Services,US,US,09,01,auto,08/2028,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,0.00,,,,True,,,False,False
22,574788567,574788567,2500.0,2391.14,2016-02-12T03:47:24,28.23,Washington Repair,US,US,05,01,auto,09/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,108.86,,,,True,,,False,False
23,574788567,574788567,2500.0,2362.91,2016-02-22T17:32:13,26.17,Washington Repair,US,US,02,01,auto,10/2028,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,137.09,,,,True,,,False,False
24,574788567,574788567,2500.0,2336.74,2016-02-28T15:53:52,215.16,staples.com,US,US,02,01,online_retail,12/2021,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,163.26,,,,False,,,False,False
25,574788567,574788567,2500.0,2121.58,2016-02-28T16:43:46,15.83,Convenient Repair,US,US,09,01,auto,06/2033,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,378.42,,,,True,,,False,False
26,574788567,574788567,2500.0,2500.00,2016-03-02T21:49:24,35.14,Shell Repair,US,US,02,01,auto,12/2019,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,True,,,False,False
27,574788567,574788567,2500.0,2464.86,2016-03-05T22:24:50,24.44,Shell Auto Body,US,US,09,08,auto,03/2024,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,35.14,,,,True,,,False,False
28,574788567,574788567,2500.0,2440.42,2016-03-09T14:41:15,139.44,Eazy Repair,US,US,05,01,auto,08/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,59.58,,,,True,,,False,False
29,574788567,574788567,2500.0,2300.98,2016-03-10T00:59:51,235.74,Fast Repair,US,US,80,01,auto,10/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,199.02,,,,True,,,False,False
30,574788567,574788567,2500.0,2065.24,2016-03-14T06:24:48,158.79,Fast Repair,US,US,09,01,auto,03/2021,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,434.76,,,,True,,,False,False
31,574788567,574788567,2500.0,2500.00,2016-04-01T20:08:33,34.84,Eazy Auto Body,US,US,02,01,auto,11/2026,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,True,,,False,False
32,574788567,574788567,2500.0,2465.16,2016-04-05T21:44:57,304.93,Washington Repair,US,US,09,01,auto,10/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,34.84,,,,True,,,False,False
33,574788567,574788567,2500.0,2160.23,2016-04-14T05:00:43,161.39,Washington Tire,US,US,80,01,auto,09/2030,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,339.77,,,,True,,,False,False
34,574788567,574788567,2500.0,1998.84,2016-04-26T04:33:33,68.66,Fast Auto Services,US,US,02,08,auto,04/2023,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,501.16,,,,True,,,False,False
35,574788567,574788567,2500.0,1930.18,2016-04-28T08:08:33,66.09,Eazy Auto Body,US,US,02,08,auto,10/2031,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,569.82,,,,True,,,False,False
36,574788567,574788567,2500.0,2500.00,2016-05-03T21:11:14,43.64,target.com,US,US,02,01,online_retail,09/2021,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,False,,,False,False
37,574788567,574788567,2500.0,2456.36,2016-05-12T00:45:51,40.25,Fast Repair,US,US,05,01,auto,06/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,43.64,,,,True,,,False,False
38,574788567,574788567,2500.0,2416.11,2016-05-24T01:35:33,215.13,Convenient Tire,US,US,09,01,auto,10/2021,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,83.89,,,,True,,,False,False
39,574788567,574788567,2500.0,2200.98,2016-05-24T01:38:03,215.13,Convenient Tire,US,US,09,01,auto,10/2021,2015-10-13,2015-10-13,206,206,8522,REVERSAL,,299.02,,,,True,,,False,False
40,574788567,574788567,2500.0,2416.11,2016-05-24T19:15:52,286.51,amazon.com,US,US,05,01,online_retail,09/2031,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,83.89,,,,False,,,False,False
41,574788567,574788567,2500.0,2129.60,2016-05-26T14:32:39,317.95,Shell Tire,US,US,09,08,auto,05/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,370.40,,,,True,,,False,False
42,574788567,574788567,2500.0,1811.65,2016-05-28T04:42:54,2.20,Fast Auto Services,US,US,05,01,auto,07/2020,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,688.35,,,,True,,,False,False
43,574788567,574788567,2500.0,2500.00,2016-06-04T18:45:39,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,0.00,,,,False,,,False,False
44,574788567,574788567,2500.0,2495.54,2016-06-11T04:40:06,140.50,Shell Tire,US,US,05,01,auto,04/2030,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,4.46,,,,True,,,False,False
45,574788567,574788567,2500.0,2355.04,2016-06-15T00:52:10,186.61,Merchants Auto Body,US,US,09,01,auto,03/2022,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,144.96,,,,True,,,False,False
46,574788567,574788567,2500.0,2500.00,2016-07-01T14:55:32,8.20,Shell Auto Body,US,US,05,01,auto,12/2030,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,0.00,,,,True,,,False,False
47,574788567,574788567,2500.0,2491.80,2016-07-03T18:33:35,203.68,Shell Auto Body,US,US,02,08,auto,05/2023,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,8.20,,,,True,,,False,False
48,574788567,574788567,2500.0,2288.12,2016-07-06T13:08:53,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,211.88,,,,False,,,False,False
49,574788567,574788567,2500.0,2283.66,2016-07-16T10:28:25,26.55,amazon.com,US,US,09,01,online_retail,04/2026,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,216.34,,,,False,,,False,False
50,574788567,574788567,2500.0,2257.11,2016-07-23T00:41:49,46.65,Fast Auto Services,US,US,05,01,auto,08/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,242.89,,,,True,,,False,False
51,574788567,574788567,2500.0,2500.00,2016-08-06T05:22:06,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,0.00,,,,False,,,False,False
52,574788567,574788567,2500.0,2495.54,2016-08-08T14:41:07,165.10,Washington Repair,US,US,09,01,auto,09/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,4.46,,,,True,,,False,False
53,574788567,574788567,2500.0,2330.44,2016-08-12T06:47:23,50.03,gap.com,US,US,09,08,online_retail,06/2021,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,169.56,,,,False,,,False,False
54,574788567,574788567,2500.0,2280.41,2016-08-16T00:10:15,142.60,Fast Tire,US,US,02,01,auto,12/2028,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,219.59,,,,True,,,False,False
55,574788567,574788567,2500.0,2137.81,2016-08-16T14:15:09,21.66,sears.com,US,US,09,01,online_retail,11/2030,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,362.19,,,,False,,,False,False
56,574788567,574788567,2500.0,2116.15,2016-08-20T07:34:29,43.18,Fast Repair,US,US,90,01,auto,04/2029,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,383.85,,,,True,,,False,False
57,574788567,574788567,2500.0,2072.97,2016-08-21T08:23:16,15.42,Eazy Auto Body,US,US,09,08,auto,03/2032,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,427.03,,,,False,,,False,False
58,574788567,574788567,2500.0,2057.55,2016-08-26T19:17:33,196.94,Eazy Tire,US,US,02,01,auto,09/2024,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,442.45,,,,True,,,False,False
59,574788567,574788567,2500.0,1860.61,2016-08-26T19:37:15,47.08,Merchants Auto Body,US,US,02,01,auto,06/2031,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,639.39,,,,True,,,False,False
60,574788567,574788567,2500.0,2500.00,2016-09-02T07:57:44,0.00,Washington Tire,US,US,09,01,auto,04/2027,2015-10-13,2015-10-13,579,579,4219,ADDRESS_VERIFICATION,,0.00,,,,False,,,False,False
61,574788567,574788567,2500.0,2500.00,2016-09-03T11:17:28,66.33,Shell Tire,US,US,09,01,auto,07/2027,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,True,,,False,False
62,574788567,574788567,2500.0,2433.67,2016-09-05T16:44:30,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,66.33,,,,False,,,False,False
63,574788567,574788567,2500.0,2429.21,2016-09-10T05:08:58,51.43,apple.com,US,US,02,01,online_retail,10/2028,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,70.79,,,,False,,,False,False
64,574788567,574788567,2500.0,2377.78,2016-09-13T04:30:05,45.39,Merchants Tire,US,US,05,01,auto,01/2033,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,122.22,,,,True,,,False,False
65,574788567,574788567,2500.0,2332.39,2016-09-14T10:50:00,171.11,Fast Auto Services,US,US,09,08,auto,02/2025,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,167.61,,,,True,,,False,False
66,574788567,574788567,2500.0,2161.28,2016-09-14T22:56:59,234.75,Ricks Auto Body,US,US,05,01,auto,12/2029,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,338.72,,,,True,,,False,False
67,574788567,574788567,2500.0,1926.53,2016-09-19T00:13:00,563.75,Merchants Auto Body,US,US,05,01,auto,01/2022,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,573.47,,,,True,,,False,False
68,574788567,574788567,2500.0,1362.78,2016-09-23T09:02:51,130.62,Merchants Auto Services,US,US,05,01,auto,12/2019,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,1137.22,,,,True,,,False,False
69,574788567,574788567,2500.0,1232.16,2016-09-24T15:26:31,11.27,Convenient Tire,US,US,02,08,auto,03/2029,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,1267.84,,,,True,,,False,False
70,574788567,574788567,2500.0,2500.00,2016-10-05T11:16:25,16.45,Eazy Repair,US,US,05,01,auto,10/2022,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,True,,,False,False
71,574788567,574788567,2500.0,2483.55,2016-10-07T07:11:22,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,16.45,,,,False,,,False,False
72,574788567,574788567,2500.0,2479.09,2016-10-07T08:51:50,46.37,Shell Repair,US,US,02,08,auto,01/2030,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,20.91,,,,True,,,False,False
73,574788567,574788567,2500.0,2432.72,2016-10-07T10:23:57,3.87,Eazy Repair,US,US,05,01,auto,10/2022,2015-10-13,2015-10-13,579,579,4219,REVERSAL,,67.28,,,,True,,,False,False
74,574788567,574788567,2500.0,2436.59,2016-10-11T00:04:18,41.42,Curves #132685,US,US,02,01,gym,10/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,63.41,,,,False,,,False,False
75,574788567,574788567,2500.0,2395.17,2016-10-13T17:02:32,37.36,Convenient Repair,US,US,05,01,auto,10/2029,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,104.83,,,,True,,,False,False
76,574788567,574788567,2500.0,2357.81,2016-10-14T10:57:11,107.85,Shell Auto Body,US,US,09,08,auto,07/2029,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,142.19,,,,True,,,False,False
77,574788567,574788567,2500.0,2249.96,2016-10-25T07:13:16,41.42,Curves #132685,US,US,02,01,gym,10/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,250.04,,,,False,,,False,False
78,574788567,574788567,2500.0,2208.54,2016-10-29T11:01:00,0.00,Fast Tire,US,US,09,08,auto,12/2026,2015-10-13,2015-10-13,579,579,4219,ADDRESS_VERIFICATION,,291.46,,,,False,,,False,False
79,574788567,574788567,2500.0,2500.00,2016-11-02T22:15:11,190.95,Eazy Auto Body,US,US,02,01,auto,08/2023,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,True,,,False,False
80,574788567,574788567,2500.0,2309.05,2016-11-06T12:10:28,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,190.95,,,,False,,,False,False
81,574788567,574788567,2500.0,2304.59,2016-11-06T20:41:48,35.40,oldnavy.com,US,US,02,01,online_retail,09/2032,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,195.41,,,,False,,,False,False
82,574788567,574788567,2500.0,2269.19,2016-11-08T06:59:12,41.42,Curves #132685,US,US,02,01,gym,10/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,230.81,,,,False,,,False,False
83,574788567,574788567,2500.0,2227.77,2016-11-22T08:29:20,41.42,Curves #132685,US,US,02,01,gym,10/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,272.23,,,,False,,,False,False
84,574788567,574788567,2500.0,2500.00,2016-12-01T08:18:57,3.32,Merchants Tire,US,US,05,01,auto,11/2030,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,0.00,,,,True,,,False,False
85,574788567,574788567,2500.0,2496.68,2016-12-05T12:50:39,41.42,Curves #132685,US,US,02,01,gym,10/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,3.32,,,,False,,,False,False
86,574788567,574788567,2500.0,2455.26,2016-12-08T00:22:08,4.46,Play Store,US,US,09,01,mobileapps,05/2024,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,44.74,,,,False,,,False,False
87,574788567,574788567,2500.0,2450.80,2016-12-11T21:22:03,1.09,Washington Auto Body,US,US,02,01,auto,11/2028,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,49.20,,,,True,,,False,False
88,574788567,574788567,2500.0,2449.71,2016-12-14T19:57:13,66.51,Convenient Repair,US,US,09,01,auto,05/2031,2015-10-13,2015-10-13,579,579,4219,PURCHASE,,50.29,,,,True,,,False,False
89,574788567,574788567,2500.0,2383.20,2016-12-19T11:53:58,34.69,Shell Auto Body,US,US,02,01,auto,02/2021,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,116.80,,,,False,,,False,False
90,574788567,574788567,2500.0,2348.51,2016-12-19T18:07:09,41.42,Curves #132685,US,US,02,01,gym,10/2029,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,151.49,,,,False,,,False,False
91,574788567,574788567,2500.0,2307.09,2016-12-24T16:14:13,1091.13,Shell Tire,US,US,05,08,auto,06/2021,2015-10-13,2015-10-13,206,206,8522,PURCHASE,,192.91,,,,False,,,False,False
92,924729945,924729945,50000.0,50000.00,2016-01-08T15:06:39,81.66,ebay.com,US,US,05,01,online_retail,05/2033,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,0.00,,,,False,,,False,False
93,924729945,924729945,50000.0,49918.34,2016-01-26T08:40:13,231.37,sears.com,US,US,02,01,online_retail,12/2021,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,81.66,,,,False,,,False,False
94,924729945,924729945,50000.0,50000.00,2016-02-05T03:55:42,365.84,gap.com,US,US,05,01,online_retail,08/2021,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,0.00,,,,False,,,False,False
95,924729945,924729945,50000.0,50000.00,2016-04-11T20:30:47,293.54,ebay.com,US,US,05,01,online_retail,02/2027,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,0.00,,,,False,,,False,False
96,924729945,924729945,50000.0,50000.00,2016-05-09T12:36:15,138.22,staples.com,US,US,05,08,online_retail,09/2031,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,0.00,,,,False,,,False,False
97,924729945,924729945,50000.0,49861.78,2016-05-12T19:26:31,54.95,sears.com,US,US,09,01,online_retail,12/2026,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,138.22,,,,False,,,False,False
98,924729945,924729945,50000.0,50000.00,2016-07-01T07:55:51,73.38,amazon.com,US,US,09,01,online_retail,03/2032,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,0.00,,,,False,,,False,False
99,924729945,924729945,50000.0,49926.62,2016-07-23T08:26:18,273.94,sears.com,US,US,02,01,online_retail,11/2020,2014-07-25,2014-07-25,205,205,9459,PURCHASE,,73.38,,,,False,,,False,False

### Working with "transactionDateTime" feature
Creating a derived features as "time_diff" , which is simply the duration between each
transaction to the very 1st transaction and "time_diff_sec" is in seconds

Note : I am removing 'NaT' value rows in "time_diff" column

In [13]:
df['transactionDateTime'] = pd.to_datetime(df['transactionDateTime'])

In [14]:
type(df['transactionDateTime'])

pandas.core.series.Series

In [15]:
df['time_diff'] = df.sort_values(['customerId','transactionDateTime']).groupby('customerId')['transactionDateTime'].diff()

In [16]:
df.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud,time_diff
0,737265056,737265056,5000.0,5000.0,2016-08-13 14:27:32,98.55,Uber,US,US,02,01,rideshare,06/2023,2015-03-14,2015-03-14,414,414,1803,PURCHASE,,0.0,,,,False,,,False,False,NaT
1,737265056,737265056,5000.0,5000.0,2016-10-11 05:05:54,74.51,AMC #191138,US,US,09,01,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,True,,,False,False,58 days 14:38:22
2,737265056,737265056,5000.0,5000.0,2016-11-08 09:18:39,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,False,,,False,False,28 days 04:12:45
3,737265056,737265056,5000.0,5000.0,2016-12-10 02:14:50,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,False,,,False,False,31 days 16:56:11
4,830329091,830329091,5000.0,5000.0,2016-03-24 21:04:46,71.18,Tim Hortons #947751,US,US,02,01,fastfood,10/2029,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.0,,,,True,,,False,False,NaT

In [17]:
df = df.dropna(subset=['time_diff'])

In [18]:
df['isFraud'].value_counts()

False    769019
True      12344
Name: isFraud, dtype: int64

In [19]:
df['time_diff_sec'] = df['time_diff'].dt.total_seconds()

In [20]:
df.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud,time_diff,time_diff_sec
1,737265056,737265056,5000.0,5000.0,2016-10-11 05:05:54,74.51,AMC #191138,US,US,09,01,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,True,,,False,False,58 days 14:38:22,5063902.0
2,737265056,737265056,5000.0,5000.0,2016-11-08 09:18:39,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,False,,,False,False,28 days 04:12:45,2434365.0
3,737265056,737265056,5000.0,5000.0,2016-12-10 02:14:50,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,False,,,False,False,31 days 16:56:11,2739371.0
5,830329091,830329091,5000.0,5000.0,2016-04-19 16:24:27,30.76,In-N-Out #422833,US,US,02,01,fastfood,01/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.0,,,,True,,,False,False,25 days 19:19:41,2229581.0
6,830329091,830329091,5000.0,5000.0,2016-05-21 14:50:35,57.28,Krispy Kreme #685312,US,US,02,01,fastfood,05/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.0,,,,True,,,False,False,31 days 22:26:08,2759168.0

In [21]:
df.describe()

,creditLimit,availableMoney,transactionAmount,currentBalance,time_diff,time_diff_sec
count,781363.000000,781363.000000,781363.000000,781363.000000,781363,7.813630e+05
mean,10763.369906,6225.779060,137.016299,4537.590846,2 days 02:54:42.205295106,1.832822e+05
std,11641.136039,8861.522276,147.736755,6467.957401,6 days 04:48:02.692938549,5.356827e+05
min,250.000000,-1005.630000,0.000000,0.000000,0 days 00:00:00,0.000000e+00
25%,5000.000000,1073.295000,33.680000,714.420000,0 days 01:49:53,6.593000e+03
50%,7500.000000,3165.820000,87.920000,2486.280000,0 days 09:20:37,3.363700e+04
75%,15000.000000,7489.940000,191.540000,5334.665000,1 days 15:18:07,1.414870e+05
max,50000.000000,50000.000000,2011.540000,47498.810000,328 days 03:50:56,2.835306e+07

### working with "cardCVV" ,"enteredCVV" features
A simple approach will be if the cvv matches then its almost genuine and vice versa

In [22]:
import numpy as np
df['cvv_match'] = np.where(df['cardCVV']==df['enteredCVV'], 0, 1)

In [23]:
df.head()

,accountNumber,customerId,creditLimit,availableMoney,transactionDateTime,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,currentExpDate,accountOpenDate,dateOfLastAddressChange,cardCVV,enteredCVV,cardLast4Digits,transactionType,echoBuffer,currentBalance,merchantCity,merchantState,merchantZip,cardPresent,posOnPremises,recurringAuthInd,expirationDateKeyInMatch,isFraud,time_diff,time_diff_sec,cvv_match
1,737265056,737265056,5000.0,5000.0,2016-10-11 05:05:54,74.51,AMC #191138,US,US,09,01,entertainment,02/2024,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,True,,,False,False,58 days 14:38:22,5063902.0,0
2,737265056,737265056,5000.0,5000.0,2016-11-08 09:18:39,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,False,,,False,False,28 days 04:12:45,2434365.0,0
3,737265056,737265056,5000.0,5000.0,2016-12-10 02:14:50,7.47,Play Store,US,US,09,01,mobileapps,08/2025,2015-03-14,2015-03-14,486,486,767,PURCHASE,,0.0,,,,False,,,False,False,31 days 16:56:11,2739371.0,0
5,830329091,830329091,5000.0,5000.0,2016-04-19 16:24:27,30.76,In-N-Out #422833,US,US,02,01,fastfood,01/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.0,,,,True,,,False,False,25 days 19:19:41,2229581.0,0
6,830329091,830329091,5000.0,5000.0,2016-05-21 14:50:35,57.28,Krispy Kreme #685312,US,US,02,01,fastfood,05/2020,2015-08-06,2015-08-06,885,885,3143,PURCHASE,,0.0,,,,True,,,False,False,31 days 22:26:08,2759168.0,0

# Droping columns

Below features/variables  can't help explaining the value of the column "isfraud".

So ,we should drop this variable because it will certainly harm the precision of our estimations.

Note 1: "transactionDateTime" feature is being removed because we already have created "time_diff" column  
Note 2: "cardCVV" ,"enteredCVV" features are also being removed as we created the "cvv_match" column

In [24]:
df.columns.values

array(['accountNumber', 'customerId', 'creditLimit', 'availableMoney',
       'transactionDateTime', 'transactionAmount', 'merchantName',
       'acqCountry', 'merchantCountryCode', 'posEntryMode',
       'posConditionCode', 'merchantCategoryCode', 'currentExpDate',
       'accountOpenDate', 'dateOfLastAddressChange', 'cardCVV',
       'enteredCVV', 'cardLast4Digits', 'transactionType', 'echoBuffer',
       'currentBalance', 'merchantCity', 'merchantState', 'merchantZip',
       'cardPresent', 'posOnPremises', 'recurringAuthInd',
       'expirationDateKeyInMatch', 'isFraud', 'time_diff',
       'time_diff_sec', 'cvv_match'], dtype=object)

# 2nd Check point

In [25]:
new_df =df.copy()

In [26]:
new_df=new_df.drop(['accountNumber', 'customerId','transactionDateTime',  'currentExpDate',
                'accountOpenDate', 'dateOfLastAddressChange', 'cardCVV', 'enteredCVV', 
                'cardLast4Digits', 'echoBuffer','merchantCity', 'merchantState', 'merchantZip',
                    'posOnPremises', 'recurringAuthInd'],axis=1 )

In [27]:
new_df.head()

,creditLimit,availableMoney,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,time_diff,time_diff_sec,cvv_match
1,5000.0,5000.0,74.51,AMC #191138,US,US,09,01,entertainment,PURCHASE,0.0,True,False,False,58 days 14:38:22,5063902.0,0
2,5000.0,5000.0,7.47,Play Store,US,US,09,01,mobileapps,PURCHASE,0.0,False,False,False,28 days 04:12:45,2434365.0,0
3,5000.0,5000.0,7.47,Play Store,US,US,09,01,mobileapps,PURCHASE,0.0,False,False,False,31 days 16:56:11,2739371.0,0
5,5000.0,5000.0,30.76,In-N-Out #422833,US,US,02,01,fastfood,PURCHASE,0.0,True,False,False,25 days 19:19:41,2229581.0,0
6,5000.0,5000.0,57.28,Krispy Kreme #685312,US,US,02,01,fastfood,PURCHASE,0.0,True,False,False,31 days 22:26:08,2759168.0,0

In [28]:
new_df=new_df.drop(['time_diff'],axis=1)

In [29]:
new_df.head()

,creditLimit,availableMoney,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,time_diff_sec,cvv_match
1,5000.0,5000.0,74.51,AMC #191138,US,US,09,01,entertainment,PURCHASE,0.0,True,False,False,5063902.0,0
2,5000.0,5000.0,7.47,Play Store,US,US,09,01,mobileapps,PURCHASE,0.0,False,False,False,2434365.0,0
3,5000.0,5000.0,7.47,Play Store,US,US,09,01,mobileapps,PURCHASE,0.0,False,False,False,2739371.0,0
5,5000.0,5000.0,30.76,In-N-Out #422833,US,US,02,01,fastfood,PURCHASE,0.0,True,False,False,2229581.0,0
6,5000.0,5000.0,57.28,Krispy Kreme #685312,US,US,02,01,fastfood,PURCHASE,0.0,True,False,False,2759168.0,0

In [30]:
new_df.replace({False: 0, True: 1}, inplace=True)

In [31]:
new_df.head()

,creditLimit,availableMoney,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,time_diff_sec,cvv_match
1,5000.0,5000.0,74.51,AMC #191138,US,US,09,01,entertainment,PURCHASE,0.0,1,0,0,5063902.0,0
2,5000.0,5000.0,7.47,Play Store,US,US,09,01,mobileapps,PURCHASE,0.0,0,0,0,2434365.0,0
3,5000.0,5000.0,7.47,Play Store,US,US,09,01,mobileapps,PURCHASE,0.0,0,0,0,2739371.0,0
5,5000.0,5000.0,30.76,In-N-Out #422833,US,US,02,01,fastfood,PURCHASE,0.0,1,0,0,2229581.0,0
6,5000.0,5000.0,57.28,Krispy Kreme #685312,US,US,02,01,fastfood,PURCHASE,0.0,1,0,0,2759168.0,0

In [32]:
new_df.describe(include='all')

,creditLimit,availableMoney,transactionAmount,merchantName,acqCountry,merchantCountryCode,posEntryMode,posConditionCode,merchantCategoryCode,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,time_diff_sec,cvv_match
count,781363.000000,781363.000000,781363.000000,781363,781363,781363,781363,781363,781363,781363,781363.000000,781363.000000,781363.000000,781363.000000,7.813630e+05,781363.000000
unique,NaN,NaN,NaN,2490,5,5,6,4,19,4,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,Uber,US,US,05,01,online_retail,PURCHASE,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,25413,769781,773560,313103,624797,200880,740344,NaN,NaN,NaN,NaN,NaN,NaN
mean,10763.369906,6225.779060,137.016299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4537.590846,0.448750,0.001330,0.015798,1.832822e+05,0.008911
std,11641.136039,8861.522276,147.736755,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6467.957401,0.497367,0.036441,0.124694,5.356827e+05,0.093978
min,250.000000,-1005.630000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000
25%,5000.000000,1073.295000,33.680000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,714.420000,0.000000,0.000000,0.000000,6.593000e+03,0.000000
50%,7500.000000,3165.820000,87.920000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2486.280000,0.000000,0.000000,0.000000,3.363700e+04,0.000000
75%,15000.000000,7489.940000,191.540000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5334.665000,1.000000,0.000000,0.000000,1.414870e+05,0.000000
max,50000.000000,50000.000000,2011.540000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47498.810000,1.000000,1.000000,1.000000,2.835306e+07,1.000000

In [33]:
new_df.isnull().sum()

creditLimit                 0
availableMoney              0
transactionAmount           0
merchantName                0
acqCountry                  0
merchantCountryCode         0
posEntryMode                0
posConditionCode            0
merchantCategoryCode        0
transactionType             0
currentBalance              0
cardPresent                 0
expirationDateKeyInMatch    0
isFraud                     0
time_diff_sec               0
cvv_match                   0
dtype: int64

# Working with Categorical data

In [34]:
# Droping "merchantName" feature because it has 2490 unique values which will lead to create huge no. of dummies
# Droping "merchantCountryCode" since in summary table it is almost like  "acqCountry"
df1 = new_df.drop(['merchantName','merchantCountryCode'],axis=1)

In [35]:
df1.head()

,creditLimit,availableMoney,transactionAmount,acqCountry,posEntryMode,posConditionCode,merchantCategoryCode,transactionType,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,time_diff_sec,cvv_match
1,5000.0,5000.0,74.51,US,09,01,entertainment,PURCHASE,0.0,1,0,0,5063902.0,0
2,5000.0,5000.0,7.47,US,09,01,mobileapps,PURCHASE,0.0,0,0,0,2434365.0,0
3,5000.0,5000.0,7.47,US,09,01,mobileapps,PURCHASE,0.0,0,0,0,2739371.0,0
5,5000.0,5000.0,30.76,US,02,01,fastfood,PURCHASE,0.0,1,0,0,2229581.0,0
6,5000.0,5000.0,57.28,US,02,01,fastfood,PURCHASE,0.0,1,0,0,2759168.0,0

In [36]:
df1['creditLimit'].unique()

array([ 5000.,  2500., 50000., 15000., 10000.,   250.,   500.,  1000.,
        7500., 20000.])

In [37]:
df1['creditLimit'].value_counts()

5000.0     200832
15000.0    138534
7500.0      97163
2500.0      74930
20000.0     68151
10000.0     56405
50000.0     48535
1000.0      36190
250.0       33760
500.0       26863
Name: creditLimit, dtype: int64

In [38]:
# Likewise checking for ;
df1['acqCountry'].unique()

array(['US', '', 'CAN', 'MEX', 'PR'], dtype=object)

In [39]:
df1['acqCountry'].value_counts()

US     769781
         4535
MEX      3109
CAN      2413
PR       1525
Name: acqCountry, dtype: int64

### Creating individual dummies for each categorical features

In [40]:
# 'creditLimit'

In [41]:
creditLimit_column =pd.get_dummies(df1['creditLimit'],drop_first=True)

In [42]:
creditLimit_column

,500.0,1000.0,2500.0,5000.0,7500.0,10000.0,15000.0,20000.0,50000.0
1,0,0,0,1,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0
5,0,0,0,1,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...
786358,0,0,0,0,0,0,0,0,1
786359,0,0,0,0,0,0,0,0,1
786360,0,0,0,0,0,0,0,0,1
786361,0,0,0,0,0,0,0,0,1
786362,0,0,0,0,0,0,0,0,1

In [43]:
# grouping 500-5000
# grouping 7500-10000
# grouping 15000-50000

In [44]:
cl1=creditLimit_column.loc[:,500.0:5000.0].max(axis=1)
cl2=creditLimit_column.loc[:,7500.0:10000.0].max(axis=1)
cl3=creditLimit_column.loc[:,15000.0:50000.0].max(axis=1)

In [45]:
# 'acqCountry'

In [46]:
acqCountry_column =pd.get_dummies(df1['acqCountry'],drop_first=True)

In [47]:
acqCountry_column

        CAN  MEX  PR  US
1         0    0   0   1
2         0    0   0   1
3         0    0   0   1
5         0    0   0   1
6         0    0   0   1
...     ...  ...  ..  ..
786358    0    0   0   1
786359    0    0   0   1
786360    0    0   0   1
786361    0    0   0   1
786362    0    0   0   1

[781363 rows x 4 columns]

In [48]:
ac1=acqCountry_column.loc[:,'US':].max(axis=1)
ac2=acqCountry_column.loc[:,'CAN':'PR'].max(axis=1)

In [49]:
type(ac1)

pandas.core.series.Series

In [50]:
# "posEntryMode"

In [51]:
df1['posEntryMode'].value_counts()

05    313103
09    234915
02    194654
90     19465
80     15195
        4031
Name: posEntryMode, dtype: int64

In [52]:
posEntryMode_column =pd.get_dummies(df1['posEntryMode'],drop_first=True)

In [53]:
pem05 = posEntryMode_column.loc[:,'05':'05'].max(axis=1)
pem09 = posEntryMode_column.loc[:,'09':'09'].max(axis=1)
pem02 = posEntryMode_column.loc[:,'02':'02'].max(axis=1)
pem90 = posEntryMode_column.loc[:,'80':'80'].max(axis=1)
pem80 = posEntryMode_column.loc[:,'80':'80'].max(axis=1)

In [54]:
type(pem05)

pandas.core.series.Series

In [55]:
# "posConditionCode"

In [56]:
df1['posConditionCode'].value_counts()

01    624797
08    148674
99      7486
         406
Name: posConditionCode, dtype: int64

In [57]:
posConditionCode_column =pd.get_dummies(df1['posConditionCode'],drop_first=True)
posConditionCode_column

        01  08  99
1        1   0   0
2        1   0   0
3        1   0   0
5        1   0   0
6        1   0   0
...     ..  ..  ..
786358   1   0   0
786359   1   0   0
786360   1   0   0
786361   0   0   1
786362   1   0   0

[781363 rows x 3 columns]

In [58]:
pcc01 = posConditionCode_column.loc[:,'01':'01'].max(axis=1)
pcc08 = posConditionCode_column.loc[:,'08':'08'].max(axis=1)
pcc99 = posConditionCode_column.loc[:,'99' :'99'].max(axis=1)

In [59]:
# "merchantCategoryCode"

In [60]:
df1['merchantCategoryCode'].unique()

array(['entertainment', 'mobileapps', 'fastfood', 'food_delivery', 'auto',
       'online_retail', 'gym', 'health', 'personal care', 'food',
       'rideshare', 'fuel', 'online_subscriptions', 'online_gifts',
       'hotels', 'airline', 'furniture', 'subscriptions', 'cable/phone'],
      dtype=object)

In [61]:
df1['merchantCategoryCode'].value_counts()

online_retail           200880
fastfood                111384
entertainment            79576
food                     74992
online_gifts             65980
rideshare                50749
hotels                   33918
fuel                     23800
subscriptions            22735
auto                     21545
health                   18977
personal care            18823
airline                  15310
mobileapps               14826
online_subscriptions     10939
furniture                 7380
food_delivery             5985
gym                       2196
cable/phone               1368
Name: merchantCategoryCode, dtype: int64

In [62]:
merchantCategoryCode_column =pd.get_dummies(df1['merchantCategoryCode'],drop_first=True)
merchantCategoryCode_column

,auto,cable/phone,entertainment,fastfood,food,food_delivery,fuel,furniture,gym,health,hotels,mobileapps,online_gifts,online_retail,online_subscriptions,personal care,rideshare,subscriptions
1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
5,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786358,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
786359,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
786360,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
786361,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
786362,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [63]:
merchantCategoryCode_column.columns.values

array(['auto', 'cable/phone', 'entertainment', 'fastfood', 'food',
       'food_delivery', 'fuel', 'furniture', 'gym', 'health', 'hotels',
       'mobileapps', 'online_gifts', 'online_retail',
       'online_subscriptions', 'personal care', 'rideshare',
       'subscriptions'], dtype=object)

In [64]:
mccArranged = [  'online_gifts', 'online_retail','online_subscriptions','mobileapps',
                 'auto','food','fuel', 'furniture', 'gym', 'health','personal care', 'hotels',
               'cable/phone', 'entertainment', 'fastfood','food_delivery','rideshare','subscriptions']

In [65]:
merchantCategoryCode_column = merchantCategoryCode_column[mccArranged]

In [66]:
merchantCategoryCode_column

,online_gifts,online_retail,online_subscriptions,mobileapps,auto,food,fuel,furniture,gym,health,personal care,hotels,cable/phone,entertainment,fastfood,food_delivery,rideshare,subscriptions
1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
786358,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
786359,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
786360,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
786361,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
786362,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [67]:
mcc1 = merchantCategoryCode_column.loc[:,'online_gifts':'mobileapps'].max(axis=1)
mcc2 = merchantCategoryCode_column.loc[:,'auto':'hotels'].max(axis=1)
mcc3 = merchantCategoryCode_column.loc[:, 'cable/phone':'subscriptions'].max(axis=1)

In [68]:
# "transactionType"

In [69]:
df1['transactionType'].value_counts()

PURCHASE                740344
REVERSAL                 20303
ADDRESS_VERIFICATION     20020
                           696
Name: transactionType, dtype: int64

In [70]:
transactionType_column =pd.get_dummies(df1['transactionType'],drop_first=True)
transactionType_column

        ADDRESS_VERIFICATION  PURCHASE  REVERSAL
1                          0         1         0
2                          0         1         0
3                          0         1         0
5                          0         1         0
6                          0         1         0
...                      ...       ...       ...
786358                     0         1         0
786359                     0         1         0
786360                     0         1         0
786361                     0         1         0
786362                     0         1         0

[781363 rows x 3 columns]

In [71]:
transactionType_column.columns.values

array(['ADDRESS_VERIFICATION', 'PURCHASE', 'REVERSAL'], dtype=object)

In [72]:
transactionType_column=transactionType_column[['PURCHASE','REVERSAL','ADDRESS_VERIFICATION']]

In [73]:
tt1= transactionType_column.loc[:,'PURCHASE':'PURCHASE'].max(axis=1)
tt2= transactionType_column.loc[:,'REVERSAL':'ADDRESS_VERIFICATION'].max(axis=1)

### Concataneting the dummies with the df1

### 3rd Checkpoint

In [74]:
df2=df1.copy()

In [75]:
# Dropping the categorical features in order to concatenate the dummies of the same.

In [76]:
df2.columns.values

array(['creditLimit', 'availableMoney', 'transactionAmount', 'acqCountry',
       'posEntryMode', 'posConditionCode', 'merchantCategoryCode',
       'transactionType', 'currentBalance', 'cardPresent',
       'expirationDateKeyInMatch', 'isFraud', 'time_diff_sec',
       'cvv_match'], dtype=object)

In [77]:
df2=df2.drop(['creditLimit','acqCountry','posEntryMode', 'posConditionCode', 'merchantCategoryCode','transactionType'],axis = 1)

In [78]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 781363 entries, 1 to 786362
Data columns (total 8 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   availableMoney            781363 non-null  float64
 1   transactionAmount         781363 non-null  float64
 2   currentBalance            781363 non-null  float64
 3   cardPresent               781363 non-null  int64
 4   expirationDateKeyInMatch  781363 non-null  int64
 5   isFraud                   781363 non-null  int64
 6   time_diff_sec             781363 non-null  float64
 7   cvv_match                 781363 non-null  int32
dtypes: float64(4), int32(1), int64(3)
memory usage: 50.7 MB

In [79]:
df2=pd.concat([cl1,cl2,cl3,df2,ac1,ac2,pem05,pem09,pem02,pem90,pem80,pcc01,pcc08,pcc99,mcc1,mcc2,mcc3,tt1,tt2],axis=1)

In [80]:
df2.head()

,0,1,2,availableMoney,transactionAmount,currentBalance,cardPresent,expirationDateKeyInMatch,isFraud,time_diff_sec,cvv_match,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
1,1,0,0,5000.0,74.51,0.0,1,0,0,5063902.0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0
2,1,0,0,5000.0,7.47,0.0,0,0,0,2434365.0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0
3,1,0,0,5000.0,7.47,0.0,0,0,0,2739371.0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0
5,1,0,0,5000.0,30.76,0.0,1,0,0,2229581.0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0
6,1,0,0,5000.0,57.28,0.0,1,0,0,2759168.0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0

In [81]:
# Rearranging the df2 features

In [82]:
df2.columns.values

array([0, 1, 2, 'availableMoney', 'transactionAmount', 'currentBalance',
       'cardPresent', 'expirationDateKeyInMatch', 'isFraud',
       'time_diff_sec', 'cvv_match', 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,
       14, 15, 16, 17], dtype=object)

In [83]:
df2_arranged=[ 'time_diff_sec', 'availableMoney', 'transactionAmount',
              'currentBalance', 'cardPresent', 'expirationDateKeyInMatch'
              , 'cvv_match', 0, 1, 2, 3, 4, 5, 6, 7, 8,
               9, 10, 11, 12, 13, 14,15,16,17,'isFraud']

In [84]:
df2=df2[df2_arranged]

In [85]:
df2.head()

,time_diff_sec,availableMoney,transactionAmount,currentBalance,cardPresent,expirationDateKeyInMatch,cvv_match,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,isFraud
1,5063902.0,5000.0,74.51,0.0,1,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0
2,2434365.0,5000.0,7.47,0.0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0
3,2739371.0,5000.0,7.47,0.0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0
5,2229581.0,5000.0,30.76,0.0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0
6,2759168.0,5000.0,57.28,0.0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,1,0,0

### 4th Check Point

In [86]:
df_preprocessed=df2.copy()

### Exporting it to csv file

In [87]:
df_preprocessed.to_csv('txn_preprocessed.csv', index=False)